# Generated by Django 5.0.1 on 2026-06-26 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_anime_id_alter_cart_id_alter_cartitem_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
