# Generated by Django 5.0.1 on 2026-06-26 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_productreviewimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewreply',
            options={'verbose_name': 'Review reply', 'verbose_name_plural': 'Review reply'},
        ),
    ]
